name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: cloudsurge.flatpak
          manifest-path: org.techtowers.CloudSurge.json

  release:
    name: "Release a tag"
    runs-on: ubuntu-latest
    needs: flatpak
    steps:
      - name: Create Release on Tag Push
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              --generate-notes
          gh release upload "$tag" cloudsurge.flatpak --repo="$GITHUB_REPOSITORY"
